production:
  amqp: amqp://guest:guest@localhost:5672
  workers: 1
  worker_types:
    tx:
      exchange: tx
      exchange_type: direct

development:
  amqp: amqp://guest:guest@localhost:5672
  workers: 1
  worker_types:
    tx:
      exchange: tx
      exchange_type: direct
